---
title: "T cell characteristics associated with irAE from ICI in melanoma"
output: pdf_document
---

 - data reproduction of https://www.nature.com/articles/s41591-021-01623-z

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load necessary libraries

```{r}

library(Seurat)
library(patchwork)
library(ggplot2)
library(dplyr)
library(tidyr)
library(tidyverse)
library(readxl)

```

# Set theme

```{r}

theme_set(
  theme_bw(20) +
    theme(panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.border = element_rect(colour="black", fill = NA, size = 1),
          axis.text = element_text(colour="black"),
          axis.ticks = element_line(colour="black"),
          axis.text.x = element_text(angle=0),
          legend.title = element_text(size = 10),
          legend.text = element_text(size = 7)))

```

# Read in TCR data

```{r}

# List of file names
file_names <- c(
  "../raw_data/GSM5694801_YUFURL_TCR.csv.gz",
  "../raw_data/GSM5694811_YUALOE_TCR.csv.gz",
  "../raw_data/GSM5694802_YUGRUS_TCR.csv.gz",
  "../raw_data/GSM5694812_YUHONEY_TCR.csv.gz",
  "../raw_data/GSM5694803_YUHERN_TCR.csv.gz",
  "../raw_data/GSM5694804_YUKEND_TCR.csv.gz",
  "../raw_data/GSM5694805_YUPIXEL_TCR.csv.gz",
  "../raw_data/GSM5694806_YUROD_TCR.csv.gz",
  "../raw_data/GSM5694798_YUCARD_TCR.csv.gz",
  "../raw_data/GSM5694808_YUTHEA_TCR.csv.gz",
  "../raw_data/GSM5694799_YUENZO_TCR.csv.gz",
  "../raw_data/GSM5694800_YUFUB_TCR.csv.gz",
  "../raw_data/GSM5694810_YUVARDO_TCR.csv.gz",
  "../raw_data/GSM5694809_YUTORY_TCR.csv.gz",
  "../raw_data/GSM5694807_YUTAUR_TCR.csv.gz",
  "../raw_data/GSM5694813_YUNANCY_TCR.csv.gz"
)

## List of patient IDs we want to include
selected_patient_IDs <- c(
  "YUCARD", "YUPIXEL", "YUENZO", "YUKEND", "YUTHEA", 
  "YUFUB", "YUTAUR", "YUVARDO", "YUGRUS", "YUFURL", 
  "YUTORY", "YUHERN", "YUROD"
)

# Filter the list of file names to include only selected patients
selected_files <- file_names[sapply(file_names, function(file_name) {
  patient_ID <- gsub(".*_(Y[A-Z]+)_.*", "\\1", file_name)
  patient_ID %in% selected_patient_IDs
})]

# Create a mapping of patient.ID to their respective suffixes
suffix_mapping <- data.frame(
  patient.ID = c(
    "YUCARD", "YUPIXEL", "YUENZO", "YUKEND", "YUTHEA", 
    "YUFUB", "YUTAUR", "YUVARDO", "YUGRUS", "YUFURL", 
    "YUTORY", "YUHERN", "YUROD"
  ),
  suffix = c(
    ".1_1", ".1_2", ".1_3", ".1_4", ".1_5", ".1_6", ".1_7", ".1_8", ".1_9", ".1_10", ".1_11", ".1_12", ".1_13"
  )
)

# Create an empty data frame to store the combined data
combined_data <- data.frame()

# Process each file and append it to the combined_data data frame
for (file_name in file_names) {
  # Read the CSV file
  data <- read_csv(file_name)
  
  # Extract patient ID and CR type (TCR or BCR) from the file name
  patient_ID <- gsub(".*_(Y[A-Z]+)_.*", "\\1", file_name)
  
  # Find the suffix based on patient ID from the mapping
  suffix <- suffix_mapping$suffix[suffix_mapping$patient.ID == patient_ID]
  
  # Add the suffix to the "Barcode" column
  data$Barcode <- paste(data$Barcode, suffix, sep = "")
  
  # Add patient ID
  data$patient.ID <- patient_ID

  # Append the data to the combined_data data frame
  combined_data <- bind_rows(combined_data, data)
}

combined_data <- combined_data %>%
  # take 1 chain per barcode per patient, don't have more data to not just choose randomly (like UMI count or something)
  group_by(Barcode, patient.ID, Chain) %>%
  slice(1) %>%
  ungroup() %>%
  rename(v_gene = 'V gene',
         d_gene = 'D gene',
         j_gene = 'J gene',
         c_gene = 'C gene',
         cdr3 = 'CDR3 AA Sequence',
         cdr3_nt = 'CDR3 NT Sequence') %>%
  pivot_wider(id_cols = c(Barcode, patient.ID), names_from = "Chain", values_from = c("v_gene", "d_gene", "j_gene", "c_gene", "cdr3", "cdr3_nt")) %>%
  # remove duplicate rows based on the "Barcode" column
  distinct(Barcode, .keep_all = TRUE)

barcoded_combined_data <- combined_data

# Set row names based on the "Barcode" column
rownames(combined_data) <- combined_data$Barcode

metadata <- combined_data %>%
  select(-Barcode)

write.csv(metadata, "../saved_data/tcr_metadata.csv")

combined_data <- combined_data %>%
  rename(TCR_name = Barcode)

```

# Prep for stitchr

```{r}

bad_alpha <- combined_data %>%
  rename(TRAV = v_gene_TRA, TRAJ = j_gene_TRA, TRBV = v_gene_TRB, TRBJ = j_gene_TRB, TRAC = c_gene_TRA, TRBC = c_gene_TRB, TRA_CDR3 = cdr3_TRA, TRB_CDR3 = cdr3_TRB) %>%
  select(TCR_name, TRAV, TRAJ, TRA_CDR3, TRBV, TRBJ, TRB_CDR3, TRAC, TRBC) %>%
  filter((is.na(TRAV)) | (is.na(TRAJ)) | (is.na(TRAC)) | (is.na(TRA_CDR3)))

stitchr_alpha_data <- combined_data %>%
  rename(TRAV = v_gene_TRA, TRAJ = j_gene_TRA, TRBV = v_gene_TRB, TRBJ = j_gene_TRB, TRAC = c_gene_TRA, TRBC = c_gene_TRB, TRA_CDR3 = cdr3_TRA, TRB_CDR3 = cdr3_TRB) %>%
  select(TCR_name, TRAV, TRAJ, TRA_CDR3, TRBV, TRBJ, TRB_CDR3, TRAC, TRBC) %>%
  filter(!(TCR_name %in% bad_alpha$TCR_name)) %>%
  mutate(TRA_leader	= NA,
         TRB_leader = NA,
         Linker = NA,
         Link_order = NA,
         TRA_5_prime_seq = NA,
         TRA_3_prime_seq = NA,
         TRB_5_prime_seq = NA,
         TRB_3_prime_seq = NA)

stitchr_alpha_data

# 5273 rows

write.table(stitchr_alpha_data, file = "../saved_data/tcrseq_tra_for_stitchr.tsv", sep = "\t", quote = FALSE, row.names = FALSE, na = "")

bad_beta <- combined_data %>%
    rename(TRAV = v_gene_TRA, TRAJ = j_gene_TRA, TRBV = v_gene_TRB, TRBJ = j_gene_TRB, TRAC = c_gene_TRA, TRBC = c_gene_TRB, TRA_CDR3 = cdr3_TRA, TRB_CDR3 = cdr3_TRB) %>%
  select(TCR_name, TRAV, TRAJ, TRA_CDR3, TRBV, TRBJ, TRB_CDR3, TRAC, TRBC) %>%
  filter((is.na(TRBV)) | (is.na(TRBJ)) | (is.na(TRBC)) | (is.na(TRB_CDR3)))

stitchr_beta_data <- combined_data %>%
  rename(TRAV = v_gene_TRA, TRAJ = j_gene_TRA, TRBV = v_gene_TRB, TRBJ = j_gene_TRB, TRAC = c_gene_TRA, TRBC = c_gene_TRB, TRA_CDR3 = cdr3_TRA, TRB_CDR3 = cdr3_TRB) %>%
  select(TCR_name, TRAV, TRAJ, TRA_CDR3, TRBV, TRBJ, TRB_CDR3, TRAC, TRBC) %>%
  filter(!(TCR_name %in% bad_beta$TCR_name)) %>%
  mutate(TRA_leader	= NA,
         TRB_leader = NA,
         Linker = NA,
         Link_order = NA,
         TRA_5_prime_seq = NA,
         TRA_3_prime_seq = NA,
         TRB_5_prime_seq = NA,
         TRB_3_prime_seq = NA)

stitchr_beta_data

# 6958 rows

write.table(stitchr_beta_data, file = "../saved_data/tcrseq_trb_for_stitchr.tsv", sep = "\t", quote = FALSE, row.names = FALSE, na = "")

```

# Prep IGoR input

```{r}

stitchr_output_alpha_df <- read_tsv("../saved_data/stitchr_tra_out.tsv") %>%
  filter(!(is.na(TRA_nt)),
         nchar(TRA_nt) > 1)

stitchr_output_alpha_df

# 5037 TCRs

write.csv(stitchr_output_alpha_df, file = "../saved_data/igor_alpha_input.csv", row.names = FALSE)

stitchr_output_beta_df <- read_tsv("../saved_data/stitchr_trb_out.tsv") %>%
  filter(!(is.na(TRB_nt)),
         nchar(TRB_nt) > 1)

stitchr_output_beta_df

# 6807 TCRs

write.csv(stitchr_output_beta_df, file = "../saved_data/igor_beta_input.csv", row.names = FALSE)

```

# Read in IGoR output


```{r}

barcoded_combined_data <- barcoded_combined_data %>%
  rename(barcode = Barcode)

igor_alpha <- read.csv("../saved_data/igor_output_alpha.csv") %>%
  rename(barcode = TCR_name) %>%
  left_join(barcoded_combined_data, by = "barcode") %>%
  select(barcode, patient.ID, v_gene_TRA, v_gene_TRB, j_gene_TRA, j_gene_TRB, c_gene_TRA, c_gene_TRB, cdr3_TRA, cdr3_TRB, pgen) %>%
  pivot_longer(cols = matches("(TRA|TRB)$"),
               names_to = c(".value", "Chain"),
               names_pattern = "^(.*)_(TRA|TRB)$") %>%
  filter(Chain == "TRA",
         pgen != "NaN")

igor_combined <- read.csv("../saved_data/igor_output_beta.csv") %>%
  rename(barcode = TCR_name) %>%
  left_join(barcoded_combined_data, by = "barcode") %>%
  select(barcode, patient.ID, v_gene_TRA, v_gene_TRB, j_gene_TRA, j_gene_TRB, c_gene_TRA, c_gene_TRB, cdr3_TRA, cdr3_TRB, pgen) %>%
  pivot_longer(cols = matches("(TRA|TRB)$"),
               names_to = c(".value", "Chain"),
               names_pattern = "^(.*)_(TRA|TRB)$") %>%
  filter(Chain == "TRB",
         pgen != "NaN") %>%
  full_join(igor_alpha, by = c("barcode", "patient.ID", "v_gene", "j_gene", "c_gene", "Chain", "pgen", "cdr3"))

igor_combined

write.csv(igor_combined, "../saved_data/tcr_metadata_with_pgen.csv")

```