---
title: "Identification of Pathogenic Immune Cell Subsets Associated with Checkpoint Inhibitor-induced Myocarditis"
output: pdf_document
---

 - data reproduction of https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9397491/
 
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load necessary libraries

```{r}

library(Seurat)
library(Matrix)
library(ggplot2)
library(dplyr)
library(tidyr)

```

# Set theme

```{r}

theme_set(
  theme_bw(20) +
    theme(panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.border = element_rect(colour="black", fill = NA, size = 1),
          axis.text = element_text(colour="black"),
          axis.ticks = element_line(colour="black"),
          axis.text.x = element_text(angle=0),
          legend.title = element_text(size = 10),
          legend.text = element_text(size = 7)))

```

# Read in TCR-seq data

```{r}

data_directory <- "../raw_data"

# Identify the pattern to extract patient IDs using regular expressions
pattern <- "GSM\\d+_([A-Z\\d\\-]+)-filtered_contig_annotations"

# Get a list of CSV files in the directory
csv_files <- list.files(data_directory, pattern = ".csv", full.names = TRUE)

# Initialize an empty list to store data frames
data_frames <- list()

# Loop through the list of CSV files
for (file in csv_files) {
  # Extract patient ID from the file name using regex
  patient_id <- gsub("GSM(\\d+)_(.*?)\\-filtered_contig_annotations.csv", "\\2", basename(file))
  
  # Read the CSV file into a data frame
  df <- read.csv(file)
  
  # Add a column for patient ID
  df$Patient_ID <- patient_id
  
  # Append the data frame to the list
  data_frames[[patient_id]] <- df
  
}

# Combine all data frames into a single data frame
combined_tcr_seq <- bind_rows(data_frames)

combined_tcr_seq

```

# Prep for stitchr

```{r}
stitchr_data <- combined_tcr_seq %>%
  group_by(barcode) %>%
  filter(chain %in% c("TRA", "TRB"),
         # remove multi chain duplicate issues (2 barcodes)
         sum(chain == "TRA") == 1 & sum(chain == "TRB") == 1) %>%
  ungroup() %>%
  select(barcode, v_gene, d_gene, j_gene, c_gene, chain, cdr3) %>%
  rename(TCR_name = barcode,
         CDR3 = `cdr3`,
         V = `v_gene`,
         J = `j_gene`,
         C = `c_gene`) %>%
  pivot_wider(names_from = chain, values_from = c(V, J, C, CDR3)) %>%
  # rename, reorder, create cols for stitchr
  rename(TRAV = V_TRA, TRAJ = J_TRA, TRBV = V_TRB, TRBJ = J_TRB, TRAC = C_TRA, TRBC = C_TRB, TRA_CDR3 = CDR3_TRA, TRB_CDR3 = CDR3_TRB) %>%
  select(TCR_name, TRAV, TRAJ, TRA_CDR3, TRBV, TRBJ, TRB_CDR3, TRAC, TRBC) %>%
  filter_all(all_vars(!is.na(.))) %>%
  filter_all(all_vars(. != "None")) %>%
  mutate(TRA_leader	= NA,
         TRB_leader = NA,
         Linker = NA,
         Link_order = NA,
         TRA_5_prime_seq = NA,
         TRA_3_prime_seq = NA,
         TRB_5_prime_seq = NA,
         TRB_3_prime_seq = NA)

stitchr_data

# 31,866 rows

write.table(stitchr_data, file = "../saved_data/tcrseq_for_stitchr.tsv", sep = "\t", quote = FALSE, row.names = FALSE)

```

# Read in stitchr output

```{r}

stitchr_output <- read.delim("../saved_data/stitchr_out.tsv", header = TRUE, sep = "\t")

# Columns that need further separation by space
columns_to_split_by_space <- c("TRA_nt", "TRA_aa", "TRB_nt", "TRB_aa", "Linked_nt")

# Split the specified columns by space
for (col_name in columns_to_split_by_space) {
  stitchr_output[[col_name]] <- sapply(stitchr_output[[col_name]], function(x) unlist(strsplit(x, " ")))
}

# Assign the column names
colnames(stitchr_output) <- c("TCR_name", "TRA_nt", "TRB_nt", "TRA_aa", "TRB_aa", "TRAV", "TRAJ", "TRA_CDR3", "TRBV", "TRBJ",
                    "TRB_CDR3", "TRAC", "TRBC", "TRA_leader", "TRB_leader", "Linker", "Link_order", 
                    "TRA_5_prime_seq", "TRA_3_prime_seq", "TRB_5_prime_seq", "TRB_3_prime_seq", "Linked_nt", 
                    "Linked_aa", "Warnings.Errors")

# Define a function to replace with NA if length is 0
replace_empty_with_na <- function(x) {
  if (length(x) == 0) {
    return(NA)
  } else {
    return(x)
  }
}

# Replace values in the specified columns with real NA
cols_to_update <- c("TRA_nt", "TRB_nt", "TRA_aa", "TRB_aa", "Linked_nt")

for (col_name in cols_to_update) {
  stitchr_output[[col_name]] <- lapply(stitchr_output[[col_name]], replace_empty_with_na)
}

stitchr_output$TRA_nt <- sapply(stitchr_output$TRA_nt, as.character)
stitchr_output$TRA_aa <- sapply(stitchr_output$TRA_aa, as.character)
stitchr_output$TRB_nt <- sapply(stitchr_output$TRB_nt, as.character)
stitchr_output$TRB_aa <- sapply(stitchr_output$TRB_aa, as.character)
stitchr_output$Linked_nt <- sapply(stitchr_output$Linked_nt, as.character)

stitchr_output

```

# Prep IGoR input

```{r}

stitchr_output_alpha_df <- stitchr_output %>%
  filter(!(is.na(TRA_nt)))

stitchr_output_alpha_df
# 9,571 rows

write.csv(stitchr_output_alpha_df, file = "../saved_data/igor_alpha_input.csv", row.names = FALSE)

stitchr_output_beta_df <- stitchr_output %>%
  filter(!(is.na(TRB_nt)))

stitchr_output_beta_df
# 21,560 rows

write.csv(stitchr_output_beta_df, file = "../saved_data/igor_beta_input.csv", row.names = FALSE)

```