---
title: "Identification of Pathogenic Immune Cell Subsets Associated with Checkpoint Inhibitor-induced Myocarditis"
output: pdf_document
---

 - data reproduction of https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9397491/
 
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load necessary libraries

```{r}

library(Seurat)
library(Matrix)
library(ggplot2)
library(dplyr)
library(tidyr)
library(stringr)
library(circlize)
library(Biostrings)

```

# Set theme

```{r}

theme_set(
  theme_bw(20) +
    theme(panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.border = element_rect(colour="black", fill = NA, size = 1),
          axis.text = element_text(colour="black"),
          axis.ticks = element_line(colour="black"),
          axis.text.x = element_text(angle=0),
          legend.title = element_text(size = 10),
          legend.text = element_text(size = 7)))

```

# Find shortest and longest CD8 TRB junction barcodes

```{r}

longest_beta_junctions <- read.csv("../saved_data/dehashed_tcr_seq_with_rna.csv") %>%
  select(barcode, Patient_ID, Chain, predicted.celltype.l1, predicted.celltype.l2, cdr3) %>%
  filter(Chain == "TRB",
         predicted.celltype.l1 == "CD8 T",
         predicted.celltype.l2 %in% c("CD8 TEM", "CD8 TCM", "CD8 Naive", "CD8 Proliferating")) %>%
  mutate(cdr3_length = nchar(cdr3)) %>%
  group_by(Patient_ID) %>%
  arrange(desc(cdr3_length)) %>%
  slice_head(n = 50) %>%
  mutate(cdr3_length_category = "long")

longest_beta_junctions

shortest_and_longest_beta_junctions <- read.csv("../saved_data/dehashed_tcr_seq_with_rna.csv") %>%
  select(barcode, Patient_ID, Chain, predicted.celltype.l1, predicted.celltype.l2, cdr3) %>%
  filter(Chain == "TRB",
         predicted.celltype.l1 == "CD8 T",
         predicted.celltype.l2 %in% c("CD8 TEM", "CD8 TCM", "CD8 Naive", "CD8 Proliferating")) %>%
  mutate(cdr3_length = nchar(cdr3)) %>%
  group_by(Patient_ID) %>%
  arrange(cdr3_length) %>%
  slice_head(n = 50) %>%
  mutate(cdr3_length_category = "short") %>%
  full_join(longest_beta_junctions)

shortest_and_longest_beta_junctions

```

# Get Seurat objects of cells with longest and shortest CD8 TRB junctions

```{r}

seurat_obj <- readRDS("../saved_data/final_seurat_T_cells.rds")

shortest_and_longest_beta_junctions_with_rna <- subset(seurat_obj, cells = shortest_and_longest_beta_junctions$barcode)

shortest_and_longest_beta_junctions_with_rna$cdr3_length_category <- if_else(
  nchar(shortest_and_longest_beta_junctions_with_rna$cdr3_TRB) > 15, 
  "long", 
  "short"
)

```

# Analyze transcriptomes of longest and shortest CD8 TRB junction cells

```{r}

# Set Seurat idents based on metadata value
Idents(shortest_and_longest_beta_junctions_with_rna) <- shortest_and_longest_beta_junctions_with_rna$cdr3_length_category

shortest_and_longest_beta_junctions_with_rna <- PrepSCTFindMarkers(shortest_and_longest_beta_junctions_with_rna)

# Find differential markers
de_markers <- FindMarkers(
  shortest_and_longest_beta_junctions_with_rna,
  ident.1 = "long",
  ident.2 = "short",
  assay = "SCT"
)

# View the differential markers
print(de_markers %>% filter(p_val_adj < 0.05))

```

# Analyze DEs

```{r}

filtered_df <- de_markers[c("KLRC2", "KLRG1", "CCR7"), , drop = FALSE]

filtered_df

#DoHeatmap(object = shortest_and_longest_beta_junctions_with_rna, features = c("KLRC2"), assay = "SCT")

# KLRC2 is an NK-associated gene, only statistically significant one here

VlnPlot(shortest_and_longest_beta_junctions_with_rna, features = c("KLRC2", "KLRG1", "CCR7"), pt.size = 0)

#Naive T cells
#CCR7

#Effector CD8 T Cells:
#KLRG1 (Killer cell lectin-like receptor G1)

```