---
title: "Identification of Pathogenic Immune Cell Subsets Associated with Checkpoint Inhibitor-induced Myocarditis"
output: pdf_document
---

 - data reproduction of https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9397491/
 
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load necessary libraries

```{r}

library(Seurat)
library(Matrix)
library(ggplot2)
library(dplyr)
library(tidyr)
library(stringr)
library(circlize)
library(vegan)

```

# Set theme

```{r}

theme_set(
  theme_bw(20) +
    theme(panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.border = element_rect(colour="black", fill = NA, size = 1),
          axis.text = element_text(colour="black"),
          axis.ticks = element_line(colour="black"),
          axis.text.x = element_text(angle=0),
          legend.title = element_text(size = 10),
          legend.text = element_text(size = 7)))

```

# Prep hydrophobicity calculator

```{r}

# Define the amino acids and their corresponding Eisenberg hydrophobicity values
amino_acids <- c("A", "R", "N", "D", "C", "Q", "E", "G", "H", "I", "L", "K", "M", "F", "P", "S", "T", "W", "Y", "V")
hydrophobicity_values <- c(0.620, -2.530, -0.780, -0.900, 0.290, -0.850, -0.740, 0.480, -0.400, 1.380, 1.060, -1.500, 0.640, 1.190, 0.120, -0.180, -0.050, 0.81, 0.26, 1.08)

# Create a data frame
hydrophobicity_df <- data.frame(Amino_Acid = amino_acids, Hydrophobicity = hydrophobicity_values)

hydrophobicity_df

calculate_hydrophobicity <- function(sequence, hydrophobicity_df) {
  sequence <- toupper(sequence)
  # Calculate the hydrophobicity scores for each amino acid, and sum them
  scores <- sapply(strsplit(sequence, '')[[1]], function(aa) {
    match_aa <- match(aa, hydrophobicity_df$Amino_Acid)
    if (!is.na(match_aa)) {
      return(hydrophobicity_df$Hydrophobicity[match_aa])
    } else {
      # If an amino acid is not found, return NA
      return(NA)
    }
  })
  # If there are any NAs in the scores, return NA; otherwise, return the sum
  if (any(is.na(scores))) {
    return(NA)
  } else {
    return(sum(scores))
  }
}

```

# Read in data

```{r}

dehashed_combined_tcr_seq <- read.csv("../saved_data/dehashed_tcr_seq.csv")
  
suffix_lookup <- tibble(
  Patient_ID = c("B1", "A10", "MCE12", "B10", "MCE13", "B12", "MCE7", "MCE6", "A8", "B11", "A9", "A6", "B9", "B13", "A5", "B14", "B2", "A1", "B3", "A2", "A3", "MCE1", "MCE2", "MCL1", "MCL3"),
  suffix = c("10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "1", "2", "3", "4", "5", "6", "7", "8", "9")
)

# Merge the lookup table to add the suffix column to the main data frame
dehashed_combined_tcr_seq <- dehashed_combined_tcr_seq %>%
  left_join(suffix_lookup, by = "Patient_ID") %>%
  mutate(barcode = paste(barcode, suffix, sep = "_"))

dehashed_combined_tcr_seq

```

# Analyze diversity

```{r}

cdr3_amino_acid_diversity_df <- dehashed_combined_tcr_seq %>%
  filter(!(is.na(cdr3)),
         chain != "Multi") %>%
  group_by(cdr3, chain, Patient_ID, irAE) %>%
  mutate(cdr3_amino_acid_count = n()) %>%
  ungroup() %>%
  group_by(Patient_ID, chain) %>%
  # Calculate Shannon diversity index (H)
  mutate(shannon = diversity(cdr3_amino_acid_count)) %>%
  slice(1) %>%
  ungroup() %>%
  select(chain, irAE, Patient_ID, shannon)

cdr3_amino_acid_diversity_df

ggplot(cdr3_amino_acid_diversity_df, aes(x = chain, y = shannon, fill = irAE)) +
  geom_boxplot() +
  labs(x = "Chain",
       y = "Shannon entropy")

# Shannon entropy: 0 means monoclonal, higher means polyclonal, weights richness (total # of unique clones) over evenness

# Filter the data for statistical test
test_data <- cdr3_amino_acid_diversity_df %>%
  filter(chain == "TRB")

# Calculate the Wilcoxon rank-sum test statistic and p-value
wilcox_result <- wilcox.test(test_data$shannon ~ test_data$irAE)

# Print the results
print(wilcox_result)

```