---
title: "Identification of Pathogenic Immune Cell Subsets Associated with Checkpoint Inhibitor-induced Myocarditis"
output: pdf_document
---

 - data mining of https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9397491/
 
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load necessary libraries

```{r}

library(Seurat)
library(Matrix)
library(ggplot2)
library(dplyr)
library(tidyr)
library(stringr)
library(circlize)
library(scales)
library(ggpubr)

```

# Set theme

```{r}

theme_set(
  theme_bw(20) +
    theme(panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.border = element_rect(colour="black", fill = NA, size = 1),
          axis.text = element_text(colour="black"),
          axis.ticks = element_line(colour="black"),
          axis.text.x = element_text(angle=0),
          legend.title = element_text(size = 10),
          legend.text = element_text(size = 7)))

```

# Read in data

```{r}

feature_df <- read.csv("../saved_data/tcr_seq_features.csv")

feature_df

```

# Prep table of cell type (l2) vs. irAE

```{r}

contingency_table <- table(feature_df$irAE, feature_df$predicted.celltype.l2)

contingency_table

# Perform Chi-square test
chi_square_result <- chisq.test(contingency_table)

# Display the test result
print(chi_square_result)

```

# Make a plot of cell type abundances within each patient by irAE group

```{r}

cell_abundance_df <- feature_df %>%
  group_by(Patient_ID, predicted.celltype.l2, irAE) %>%
  summarize(count = n()) %>%
  ungroup() %>%
  group_by(Patient_ID) %>%
  mutate(normalized_count = count / sum(count))

cell_abundance_df

ggplot(cell_abundance_df, aes(x = predicted.celltype.l2, y = log10(normalized_count), fill = irAE)) +
  geom_boxplot() +
  labs(x = "", fill = "irAE", y = "Normalized cell\nproportion (log10)") +
  scale_y_continuous(expand = expansion(mult = c(0.1, 0.5)), breaks = pretty_breaks(n = 3)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 10))

```

# Import pgen data

```{r}

igor_alpha <- read.csv("../saved_data/igor_output_alpha.csv") %>%
  dplyr::rename(TRA_pgen = pgen) %>%
  filter(!(is.na(TRA_pgen)),
         TRA_pgen != "NaN")

igor_combined <- read.csv("../saved_data/igor_output_beta.csv") %>%
  dplyr::rename(TRB_pgen = pgen) %>%
  filter(!(is.na(TRB_pgen)),
         TRB_pgen != "NaN") %>%
  full_join(igor_alpha, by = c("TCR_name", "TRA_nt", "TRB_nt", "TRA_aa", "TRB_aa", "TRAV", "TRAJ", "TRA_CDR3", "TRBV", "TRBJ", "TRB_CDR3", "TRAC", "TRBC", "TRA_leader", "TRB_leader", "Linker", "Link_order", "TRA_5_prime_seq", "TRA_3_prime_seq", "TRB_5_prime_seq", "TRB_3_prime_seq", "Linked_nt", "Linked_aa", "Warnings.Errors")) %>%
  select(TCR_name, TRA_CDR3, TRB_CDR3, TRA_pgen, TRB_pgen) %>%
  mutate(TRA_pgen = as.character(TRA_pgen),
         TRB_pgen = as.character(TRB_pgen))

```

# Plot abundance vs. CDR3 length or pgen

```{r}

abundance_df <- igor_combined %>%
  pivot_longer(cols = matches("^(TRA|TRB)"),
               names_to = c("Chain", ".value"),
               names_pattern = "^(TRA|TRB)_(.*)$") %>%
  dplyr::rename(barcode = TCR_name,
         cdr3 = CDR3) %>%
  mutate(pgen = as.numeric(pgen)) %>%
  right_join(feature_df, by = c("barcode", "Chain", "cdr3")) %>%
  group_by(Patient_ID, cdr3_nt, chain, v_gene, j_gene) %>%
  mutate(count = n()) %>%
  slice(1) %>%
  ungroup() %>%
  select(predicted.celltype.l1, predicted.celltype.l2, count, Patient_ID, irAE, barcode, Chain, cdr3, cdr3_length, pgen) %>%
  mutate(irAE = paste("irAE:", irAE))

abundance_df

# Plot with best-fit liness
ggplot(abundance_df %>% filter(predicted.celltype.l1 == "CD8 T" & Chain == "TRB"),
       aes(x = log10(count), y = cdr3_length)) +
  geom_point(alpha = 0.3) +
  geom_smooth(method = "lm", se = FALSE, col = "blue") +
  facet_wrap(~ irAE, scales = "free_y") +
  labs(x = "CD8 TRB clonotype abundance (log10)", fill = "irAE", y = "CD8 TRB CDR3 length") +
  scale_y_continuous(expand = expansion(mult = c(0.1, 0.5)), breaks = pretty_breaks(n = 3))

# Plot with best-fit lines
ggplot(abundance_df %>% filter(predicted.celltype.l1 == "CD8 T" & Chain == "TRB"),
       aes(x = log10(count), y = log10(pgen))) +
  geom_point(alpha = 0.3) +
  geom_smooth(method = "lm", se = FALSE, col = "blue") +
  facet_wrap(~ irAE, scales = "free_y") +
  labs(x = "CD8 TRB clonotype abundance (log10)", fill = "irAE", y = "CD8 TRB pgen (log10)") +
  scale_y_continuous(expand = expansion(mult = c(0.1, 0.5)), breaks = pretty_breaks(n = 3))

```