---
title: "Identification of Pathogenic Immune Cell Subsets Associated with Checkpoint Inhibitor-induced Myocarditis"
output: pdf_document
---

 - data mining of https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9397491/
 
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load necessary libraries

```{r}

library(ggplot2)
library(dplyr)
library(tidyr)
library(VennDiagram)
library(scales)
library(ggpubr)

```

# Set theme

```{r}

theme_set(
  theme_bw(20) +
    theme(panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.border = element_rect(colour="black", fill = NA, size = 1),
          axis.text = element_text(colour="black"),
          axis.ticks = element_line(colour="black"),
          axis.text.x = element_text(angle=0),
          legend.title = element_text(size = 10),
          legend.text = element_text(size = 7)))

```

# Read in data

```{r}

combined_data <- read.csv("../saved_data/tcr_seq_features.csv")

combined_data

```

# Look at public vs. private

```{r}

public_df_list <- combined_data %>%
  group_by(cdr3) %>%
  filter(n_distinct(Patient_ID) > 1) %>%
  mutate(barc_chain = paste(barcode, chain, sep = ""))

public_df_list

private_df_list <- combined_data %>%
  group_by(cdr3) %>%
  filter(n_distinct(Patient_ID) == 1) %>%
  mutate(barc_chain = paste(barcode, chain, sep = "")) %>%
  group_by(Patient_ID, cdr3, chain, v_gene, j_gene) %>%
  # exclude singletons
  filter(n() > 1)

private_df_list

```

# Look at TCR convergence

```{r}

convergence_within_patients <- combined_data %>%
  select(Patient_ID, barcode, Chain, cdr3, cdr3_nt, v_gene, d_gene, j_gene, c_gene) %>%
  group_by(cdr3, Patient_ID) %>%
  filter(n_distinct(cdr3_nt) > 1) %>%
  ungroup()

convergence_within_patients

convergence_across_patients <- combined_data %>%
  mutate(barc_chain = paste(barcode, chain, sep = "")) %>%
  group_by(cdr3) %>%
  mutate(distinct_cdr3_nt_count = n_distinct(cdr3_nt)) %>%
  filter(distinct_cdr3_nt_count > 1)

convergence_across_patients

# do see more convergence across patients as expected, and they are mostly in public TCRs also as expected

```

# Look at overlap between public and converged

```{r}

# Create a Venn diagram
#venn.plot <- venn.diagram(
#  x = list(A = public_df$barcode, B = convergence_df$barcode),
#  category.names = c("Public TCRs", "Converged TCRs"),
#  filename = NULL,
#  output = TRUE
#)

# Display the Venn diagram
#grid.draw(venn.plot)

```

# Contingency tables for publicity, privicity, convergence for TRA/TRB comparing irAE groups

```{r}

convergence_publicity_privicity_df <- combined_data %>%
  mutate(barc_chain = paste(barcode, chain, sep = "")) %>%
  mutate(publicity = if_else(barc_chain %in% public_df_list$barc_chain, "Yes", "No"),
         privicity = if_else(barc_chain %in% private_df_list$barc_chain, "Yes", "No"),
         convergence = if_else(barc_chain %in% convergence_across_patients$barc_chain, "Yes", "No")) %>%
  group_by(Patient_ID, cdr3, chain, v_gene, j_gene) %>%
  # look at just unique clonotypes from each patient
  dplyr::slice(1)

public_counts <- convergence_publicity_privicity_df %>%
  group_by(publicity, irAE, predicted.celltype.l1, Chain) %>%
  summarize(count = n()) %>%
  ungroup() %>%
  group_by(publicity, Chain, predicted.celltype.l1) %>%
  mutate(fraction = count/sum(count))

public_counts

ggplot(public_counts, aes(x = publicity, y = fraction, fill = irAE)) +
  geom_bar(stat = "identity", position = "stack") +
  facet_wrap(~Chain + predicted.celltype.l1) +
  labs(x = "Public", y = "Fraction") +
  scale_y_continuous(breaks = seq(0, 1, by = 0.5))

private_counts <- convergence_publicity_privicity_df %>%
  group_by(privicity, irAE, predicted.celltype.l1, Chain) %>%
  summarize(count = n()) %>%
  ungroup() %>%
  group_by(privicity, Chain, predicted.celltype.l1) %>%
  mutate(fraction = count/sum(count))
 
private_counts

ggplot(private_counts, aes(x = privicity, y = fraction, fill = irAE)) +
  geom_bar(stat = "identity", position = "stack") +
  facet_wrap(~Chain + predicted.celltype.l1) +
  labs(x = "Private", y = "Fraction") +
  scale_y_continuous(breaks = seq(0, 1, by = 0.5))

convergence_counts <- convergence_publicity_privicity_df %>%
  group_by(convergence, irAE, Chain, predicted.celltype.l1) %>%
  summarize(count = n()) %>%
  ungroup() %>%
  group_by(convergence, Chain, predicted.celltype.l1) %>%
  mutate(fraction = count/sum(count))

convergence_counts

ggplot(convergence_counts, aes(x = convergence, y = fraction, fill = irAE)) +
  geom_bar(stat = "identity", position = "stack") +
  facet_wrap(~Chain + predicted.celltype.l1) +
  labs(x = "Converged", y = "Fraction") +
  scale_y_continuous(breaks = seq(0, 1, by = 0.5))

```

# Overlay convergence, publicity, privicity onto UMAP

```{r}

T_cells <- readRDS("../saved_data/final_seurat_T_cells.rds")
```

```{r}

metadata <- T_cells@meta.data
  
metadata$barcode <- rownames(metadata)

metadata

metadata <- metadata %>%
  mutate(barc_chain = paste(barcode, chain, sep = "")) %>%
  mutate(publicity = if_else(barc_chain %in% public_df_list$barc_chain, "Yes", "No"),
         privicity = if_else(barc_chain %in% private_df_list$barc_chain, "Yes", "No"),
         convergence = if_else(barc_chain %in% convergence_across_patients$barc_chain, "Yes", "No"))

T_cells$publicity <- metadata$publicity
T_cells$privicity <- metadata$privicity
T_cells$convergence <- metadata$convergence

DimPlot(just_T_cells, reduction = "umap", group.by = "publicity")

# just make separate plots for TRA/TRB as they're in same cell but plots may look different

```