---
title: "Identification of Pathogenic Immune Cell Subsets Associated with Checkpoint Inhibitor-induced Myocarditis"
output: pdf_document
---

 - data mining of https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9397491/
 
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load necessary libraries

```{r}

library(Seurat)
library(Matrix)
library(ggplot2)
library(dplyr)
library(tidyr)
library(stringr)
library(circlize)

```

# Set theme

```{r}

theme_set(
  theme_bw(20) +
    theme(panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.border = element_rect(colour="black", fill = NA, size = 1),
          axis.text = element_text(colour="black"),
          axis.ticks = element_line(colour="black"),
          axis.text.x = element_text(angle=0),
          legend.title = element_text(size = 10),
          legend.text = element_text(size = 7)))

```

# Read in IMGT data (for V/J allele calls)

```{r}

imgt_df_1_alpha <- read.csv("../saved_data/myocarditis_fixed_tra/1_Summary.csv") %>%
  mutate(v_allele = str_extract(V.GENE.and.allele, "\\*([0-9]{2})"),
         v_gene = str_extract(V.GENE.and.allele, "TRA[^*]+"),
         j_allele = str_extract(J.GENE.and.allele, "\\*([0-9]{2})"),
         j_gene = str_extract(J.GENE.and.allele, "TRA[^*]+"),
         chain = "TRA") %>%
  select(Sequence.ID, v_gene, v_allele, j_gene, j_allele, AA.JUNCTION, chain) %>%
  rename(barcode = Sequence.ID, cdr3 = AA.JUNCTION)

imgt_df_1_alpha

imgt_df_1_beta <- read.csv("../saved_data/myocarditis_fixed_trb/1_Summary.csv") %>%
  mutate(v_allele = str_extract(V.GENE.and.allele, "\\*([0-9]{2})"),
         v_gene = str_extract(V.GENE.and.allele, "TRB[^*]+"),
         j_allele = str_extract(J.GENE.and.allele, "\\*([0-9]{2})"),
         j_gene = str_extract(J.GENE.and.allele, "TRB[^*]+"),
         chain = "TRB") %>%
  select(Sequence.ID, V.GENE.and.allele, v_gene, v_allele, j_gene, j_allele, AA.JUNCTION, chain) %>%
  rename(barcode = Sequence.ID, cdr3 = AA.JUNCTION) %>%
  filter(!(str_detect(V.GENE.and.allele, "or"))) %>%
  select(-V.GENE.and.allele)

imgt_df_1_beta
# 675 rows have V.GENE.and.allele "Homsap TRBV6-2*01 F, or Homsap TRBV6-3*01 F", only or situation

imgt_df_1 <- imgt_df_1_alpha %>%
  full_join(imgt_df_1_beta, by = c("barcode", "cdr3", "v_gene", "v_allele", "j_gene", "j_allele", "chain"))

imgt_df_1

```

# Join IMGT with original TCRseq data, join with VDJdb data

```{r}

vdjdb <- read.csv("../../vdjdb_11_21_23.tsv", sep = "\t") %>%
  select(-Reference, -Method, -Meta, -CDR3fix) %>%
  rename(Chain = Gene,
         cdr3 = CDR3,
         v_gene = V,
         j_gene = J)

vdjdb

tcr_seq <- read.csv("../saved_data/tcr_seq_features.csv") %>%
  select(-X) %>%
  full_join(imgt_df_1, by = c("barcode", "v_gene", "j_gene", "chain", "cdr3")) %>%
  filter(!(is.na(v_allele)),
         !(is.na(j_allele))) %>%
  # 879 rows lost, mostly from or J gene calls for TRB
  mutate(v_gene = paste(v_gene, v_allele, sep = ""),
         j_gene = paste(j_gene, j_allele, sep = "")) %>%
  select(-v_allele, -j_allele) %>%
  left_join(vdjdb, by = c("Chain", "v_gene", "j_gene", "cdr3"))

tcr_seq

```

# Inspect species of antigen specificities

```{r}

plot_df <- tcr_seq %>%
  filter(!(is.na(irAE))) %>%
  group_by(Epitope.species, irAE, Chain) %>%
  summarize(count = n()) %>%
  mutate(test = log10(count)) %>%
  arrange(-count) %>%
  print()

ggplot(plot_df, aes(x = reorder(Epitope.species, -count), y = log10(count), fill = irAE)) +
  geom_bar(stat = "identity", position = "dodge", width = 0.7) +
  facet_wrap(~Chain) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1, size = 8)) +
  labs(x = "Epitope species", y = "TCR count (log10)")

```

# Inspect TRB CMV and EBV taking into account different patients have different numbers of TCRs sampled

```{r}

patient_counts <- tcr_seq %>%
  filter(!(is.na(Patient_ID))) %>%
  group_by(Patient_ID) %>%
  summarize(patient_tcr_seq_count = n())

plot_df <- tcr_seq %>%
  filter(Epitope.species %in% c("CMV", "EBV"),
         Chain == "TRB") %>%
  group_by(Epitope.species, irAE, Patient_ID) %>%
  summarize(raw_count = n()) %>%
  left_join(patient_counts, by = "Patient_ID") %>%
  mutate(count = raw_count / patient_tcr_seq_count)

ggplot(plot_df, aes(x = Patient_ID, y = 100*count, fill = irAE)) +
  geom_bar(stat = "identity") +
  facet_wrap(~ Epitope.species, scales = "free_y") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1, size = 8)) +
  labs(x = "Patient ID", y = "Antigen-specific TRBs (%)")

```

# Inspect human specific TCRs

```{r}

plot_df <- tcr_seq %>%
  filter(!(is.na(irAE)),
         Epitope.species == "HomoSapiens") %>%
  group_by(Epitope.gene, irAE, Chain) %>%
  summarize(count = n()) %>%
  arrange(-count) %>%
  print()

ggplot(plot_df, aes(x = reorder(Epitope.gene, -count), y = log10(count), fill = irAE)) +
  geom_bar(stat = "identity", position = "dodge", width = 0.7) +
  facet_wrap(~Chain) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1, size = 8)) +
  labs(x = "Epitope gene", y = "TCR count (log10)")

patient_counts <- tcr_seq %>%
  filter(!(is.na(Patient_ID))) %>%
  group_by(Patient_ID) %>%
  summarize(patient_tcr_seq_count = n())

plot_df <- tcr_seq %>%
  filter(Epitope.species == "HomoSapiens",
         Epitope.gene %in% c("BST2", "MLANA")) %>%
  group_by(Epitope.species, Epitope.gene, irAE, Patient_ID, orig.ident) %>%
  summarize(raw_count = n()) %>%
  left_join(patient_counts, by = "Patient_ID") %>%
  mutate(count = raw_count / patient_tcr_seq_count)

ggplot(plot_df %>% filter(Epitope.gene %in% c("BST2", "MLANA")), aes(x = Patient_ID, y = 100*count, fill = irAE)) +
  geom_bar(stat = "identity") +
  facet_wrap(~ Epitope.gene, scales = "free_y") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1, size = 8)) +
  labs(x = "Patient ID", y = "Antigen-specific TCRs (%)")

# Melanoma patients: 
# A6, A8, B3-5, B12, MCE12

# Vitiligo
# B3

```