---
title: "Thomas bioRxiv"
output: pdf_document
---
 
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load necessary libraries

```{r}

library(ggplot2)
library(dplyr)
library(stringr)
library(tidyr)
library(tcrGraph)
library(tidyverse)
library(igraph)
library(graphlayouts)
library(ggraph)
library(viridis)
library(gridExtra)

```

# Set theme

```{r}

theme_set(
  theme_bw(20) +
    theme(panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.border = element_rect(colour="black", fill = NA, size = 1),
          axis.text = element_text(colour="black"),
          axis.ticks = element_line(colour="black"),
          axis.text.x = element_text(angle=0),
          legend.title = element_text(size = 10),
          legend.text = element_text(size = 7)))

```

# Make highly expanded TCR df

```{r}

metadata <- data.frame(
  patient_id = c("MC_2", "SIC_13", "SIC_19", "SIC_31", "SIC_32", "SIC_36", "SIC_40", "SIC_43", "SIC_53", "MC_1", "MC_9", "SIC_71", "SIC_89", "SIC_76", "SIC_94", "SIC_97", "SIC_100", "SIC_109", "SIC_121", "SIC_126", "SIC_134", "SIC_140", "SIC_141", "SIC_172", "SIC_186", "SIC_187", "SIC_188", "SIC_196"),
  simplified_patient_id = c("HC7", "HC1", "IHC3", "IHC4", "C7", "C8", "C9", "C10", "IHC5", "HC6", "HC8", "C11", "C12", "C14", "IHC6", "C13", "C1", "IHC1", "C2", "C3", "C4", "C5", "C6", "IHC2", "HC2", "HC3", "HC4", "HC5")) %>%
  mutate(group = case_when(
    startsWith(simplified_patient_id, "H") ~ "No ICI",
    startsWith(simplified_patient_id, "I") ~ "ICI no colitis",
    startsWith(simplified_patient_id, "C") ~ "ICI colitis"))

tcrs <- read.csv("../saved_data/tcr_graph_input.csv") %>%
  dplyr::select(-X) %>%
  pivot_longer(cols = matches("(TRA|TRB)$"),
               names_to = c(".value", "chain"),
               names_pattern = "^(.*)_(TRA|TRB)$") %>%
  filter(!(is.na(v_gene)),
         !(is.na(j_gene)),
         !(is.na(cdr3))) %>%
  #mutate(clonotype = paste(v_gene, j_gene, cdr3, sep = "_")) %>%
  #group_by(orig.ident, clonotype, chain) %>%
  #mutate(count = n()) %>%
  #ungroup() %>%
  # look at highly expanded per patient
  #group_by(orig.ident, chain) %>%
  #arrange(-count) %>%
  #dplyr::slice_head(n = 350) %>%
  #ungroup() %>%
  dplyr::rename(libid = TCR_name) %>%
  mutate(patient_id = str_extract(orig.ident, "SIC_[0-9]+")) %>%
  left_join(metadata, by = "patient_id")

tcrs

```

# Make TCR graph with Igraph: no irAE

```{r}

no_irae_tcrs <- tcrs %>%
  filter(group == "ICI no colitis") %>%
  # exclude singletons
  group_by(libid) %>%
  filter(n() > 1) %>%
  ungroup()

no_irae_tcr_graph <- makeTcrGraph(no_irae_tcrs, link = "nt")

no_irae_tcr_igraph <- tcrGraphToIgraph(no_irae_tcr_graph)

V(no_irae_tcr_igraph)$`Number of Cells` <- V(no_irae_tcr_igraph)$value
V(no_irae_tcr_igraph)$Chain <- V(no_irae_tcr_igraph)$group

dev.new(width = 9.5, length = 8)
theme_set(theme_bw(20) + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + theme(legend.key = element_blank()))
ggraph(no_irae_tcr_igraph, "fr") +
    #geom_edge_link(
    #    edge_width = 1,
    #    #edge_color = edgeColor
    #) +
    geom_node_point(
        aes(fill = Chain, size = `Number of Cells`),
        shape = 21,
        color = "black"
    ) +
    #scale_fill_manual(values = nodePalette) +
    guides(fill = guide_legend(override.aes = list(size = 5))) +
    ggtitle("no irAE TCRs")

# Compute the average connectivity
num_edges <- ecount(no_irae_tcr_igraph)
num_vertices <- vcount(no_irae_tcr_igraph)
average_connectivity <- 2 * num_edges / num_vertices

# Print the results
cat("Average Connectivity (no irAE):", average_connectivity, "\n")
cat("Number of Edges (no irAE):", num_edges, "\n")
cat("Number of Vertices (no irAE):", num_vertices, "\n")

```

# # Make TCR graph with Igraph: yes irAE

```{r}

irae_tcrs <- tcrs %>%
  filter(group == "ICI colitis") %>%
  # exclude singletons
  group_by(libid) %>%
  filter(n() > 1) %>%
  ungroup()

irae_tcr_graph <- makeTcrGraph(irae_tcrs, link = "nt")

irae_tcr_igraph <- tcrGraphToIgraph(irae_tcr_graph)

V(irae_tcr_igraph)$`Number of Cells` <- V(irae_tcr_igraph)$value
V(irae_tcr_igraph)$Chain <- V(irae_tcr_igraph)$group

dev.new(width = 9.5, length = 8)
theme_set(theme_bw(20) + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + theme(legend.key = element_blank()))
ggraph(irae_tcr_igraph, "fr") +
    geom_edge_link(
        edge_width = 1,
        #edge_color = edgeColor
    ) +
    geom_node_point(
        aes(fill = Chain, size = `Number of Cells`),
        shape = 21,
        color = "black"
    ) +
    #scale_fill_manual(values = nodePalette) +
    guides(fill = guide_legend(override.aes = list(size = 5))) +
    ggtitle("irAE TCRs")

# Compute the average connectivity
num_edges <- ecount(irae_tcr_igraph)
num_vertices <- vcount(irae_tcr_igraph)
average_connectivity <- 2 * num_edges / num_vertices

# Print the results
cat("Average Connectivity (irAE):", average_connectivity, "\n")
cat("Number of Edges (irAE):", num_edges, "\n")
cat("Number of Vertices (irAE):", num_vertices, "\n")

```