---
title: "T cell characteristics associated with irAE from ICI in melanoma"
output: pdf_document
---

 - data reproduction of https://www.nature.com/articles/s41591-021-01623-z

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load necessary libraries

```{r}

library(Seurat)
library(patchwork)
library(ggplot2)
library(dplyr)
library(tidyr)
library(tidyverse)

```

# Set theme

```{r}

theme_set(
  theme_bw(20) +
    theme(panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.border = element_rect(colour="black", fill = NA, size = 1),
          axis.text = element_text(colour="black"),
          axis.ticks = element_line(colour="black"),
          axis.text.x = element_text(angle=0),
          legend.title = element_text(size = 10),
          legend.text = element_text(size = 7)))

```

# Read in data

```{r}

melanoma_T_cells_cell_type_clustered <- readRDS("../saved_data/cell_type_clustered.rds")

```

# Read in TCR, BCR data

```{r}

#GSM5694801_YUFURL_TCR.csv.gz
#GSM5694811_YUALOE_TCR.csv.gz
#GSM5694802_YUGRUS_TCR.csv.gz
#GSM5694812_YUHONEY_TCR.csv.gz
#GSM5694803_YUHERN_TCR.csv.gz
#GSM5694804_YUKEND_TCR.csv.gz
#GSM5694805_YUPIXEL_TCR.csv.gz
#GSM5694806_YUROD_TCR.csv.gz
#GSM5694798_YUCARD_TCR.csv.gz
#GSM5694808_YUTHEA_TCR.csv.gz
#GSM5694799_YUENZO_TCR.csv.gz
#GSM5694800_YUFUB_TCR.csv.gz
#GSM5694810_YUVARDO_TCR.csv.gz
#16 TCRs
#GSM5694809_YUTORY_TCR.csv.gz
#GSM5694807_YUTAUR_TCR.csv.gz
#GSM5694813_YUNANCY_TCR.csv.gz


#GSM5694821_YUPIXEL_BCR.csv.gz
#GSM5694822_YUROD_BCR.csv.gz
#GSM5694823_YUTAUR_BCR.csv.gz
#GSM5694814_YUCARD_BCR.csv.gz
#GSM5694824_YUTHEA_BCR.csv.gz
#GSM5694815_YUENZO_BCR.csv.gz
#GSM5694825_YUTORY_BCR.csv.gz
#GSM5694816_YUFUB_BCR.csv.gz
#GSM5694826_YUVARDO_BCR.csv.gz
#GSM5694817_YUFURL_BCR.csv.gz
#GSM5694818_YUGRUS_BCR.csv.gz
#GSM5694819_YUHERN_BCR.csv.gz
#GSM5694820_YUKEND_BCR.csv.gz

#13 BCRs

test <- read_csv("../raw_data/GSM5694798_YUCARD_TCR.csv.gz", row_names=FALSE)

rownames(test) <- test[['Barcode']]

test

# set barcodes as rownames.
#rownames(tcr) <- tcr[,1]
#tcr[,1] <- NULL
#colnames(tcr) <- paste(type, colnames(tcr), sep="_")
# Add to the Seurat object's metadata.
#clono_seurat <- AddMetaData(object=seurat_obj, metadata=tcr)
#return(clono_seurat)

```

# Assess effective doublet rate

```{r}

# cross-reference cellular barcodes with single-cell BCR (scBCR) and TCR (scTCR) clonotypes
# determine (1) the percentage of non-T cells anomalously mapped to TCR clonotypes (denoted m) and (2) the frequency (recovery rate) of annotated T cells with a matching scTCR clonotype (denoted f), calculate an effective double rate (m/f) (should get 2.2%)
# do the same for scBCR clonotypes mapping to non-B cells (should also get 2.2%)

# eliminate all single cells with aberrant expression of TCR or BCR clonotypic sequences
# repeat PCA, UMAP and FindClusters after eliminating these cells, now should get 32 clusters
# Two red blood cell clusters, marked by very high HBB expression, should remain, remove them from the analysis
# do one final round of PCA, UMAP and FindClusters, yielding a final set of 32 clusters (states)

```

# Analyze CD4 T cell subclusters

```{r}

# CD4 T cell state 5, lacks expression of CCR7 and SELL (CD62L), consistent with CD4 TEM, see association with severe iRAE development, so I'll need to find this same subcluster they find (combine with subcluster 3)

# maybe start with DEGs across subtypes of CD4 T cells, should see 2 of them closely match each other (their subclusters 3 and 5)

#rbc_filtered_immune.combined %>%
#    group_by(cluster) %>%
#    top_n(n = 10, wt = avg_log2FC) -> top10
#DoHeatmap(pbmc, features = top10$gene) + NoLegend()

```