---
title: "Identification of Pathogenic Immune Cell Subsets Associated with Checkpoint Inhibitor-induced Myocarditis"
output: pdf_document
---

 - data reproduction of https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9397491/
 
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load necessary libraries

```{r}

library(Seurat)
library(Matrix)
library(ggplot2)
library(dplyr)
library(tidyr)
library(stringr)
library(circlize)

```

# Set theme

```{r}

theme_set(
  theme_bw(20) +
    theme(panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.border = element_rect(colour="black", fill = NA, size = 1),
          axis.text = element_text(colour="black"),
          axis.ticks = element_line(colour="black"),
          axis.text.x = element_text(angle=0),
          legend.title = element_text(size = 10),
          legend.text = element_text(size = 7)))

```

# Read in data

```{r}

tcrsQC <- load("../saved_data/20231108_circos_R_workspace_P474.RData")

```

# Inspect data

```{r}

tcrsQC

```

# Thomas circos code

```{r createObjectsPlotCircosQcCd8, dependson="filterTcrsQcPass"}
# run clonality estimation

## define columns for sample and group variables
sampleColumnCircosQcCd8 <- "donorId"
groupColumnCircosQcCd8 <- "Cell.Type_CD8"

# Filter TCRs to those of interest
tcrsCircosQcCd8 <-
  tcrsQC %>%
  dplyr::filter(
    cellType == "CD8",
    Cell.Type_CD8 %in% c("Naïve", "TEM", "TEMRA", "TSCM", "TCM"),
    chain %in% c("alpha", "beta"),
    !(libid %in% maitSummary$libid)) # remove MAIT cells

# Add sample info (sample and group) to the tcr df
tcrsCircosQcCd8 <-
  left_join(
    tcrsCircosQcCd8,
    annotatedMetricsQC %>% dplyr::select(libid, all_of(c(sampleColumnCircosQcCd8, groupColumnCircosQcCd8))))
# check for columns duplicated in tcr and annotation.merged
# grep("\\.[xy]", colnames(tcrsCircosQcCd8), value=TRUE)
# none; good!

# sort tcrsCircosQcCd8 by the variables of interest (which might be unnecessary?)
tcrsCircosQcCd8 <-
  tcrsCircosQcCd8[
    order(tcrsCircosQcCd8[, groupColumnCircosQcCd8, drop = TRUE],
      tcrsCircosQcCd8[, sampleColumnCircosQcCd8, drop = TRUE]), ]

# Make a new numeric libid number for each lib, in the order libs have been arranged, to facilitate plotting order
tcrsCircosQcCd8 <-
  tcrsCircosQcCd8 %>%
  dplyr::rename(old.libid = libid)
tcrsCircosQcCd8$libid <-
  tcrsCircosQcCd8$old.libid %>%
  match(unique(.))

### determine expanded TCRs
tcrChainMatchesCircosQcCd8 <- match_TCR_chains(tcrsCircosQcCd8)
tcrChainMatchesCircosQcCd8[, c("tcr1", "tcr2")] <-
  lapply(tcrChainMatchesCircosQcCd8[, c("tcr1", "tcr2")], as.character)

### tabulate number of chains matching between cells
tcrLinksCircosQcCd8 <-
  tabulate_shared_TCR_chains(tcrChainMatchesCircosQcCd8) %>%
  dplyr::arrange(tcr1)

### create new data frame to store cell information (colors on various rings)
tcrCellsCircosQcCd8 <- tcrsCircosQcCd8

# Set up project colors for incorporation into tcr_cells
samplePalCircosQcCd8 <-
  big_colorblind_pal(length(unique(tcrsCircosQcCd8[, sampleColumnCircosQcCd8, drop = TRUE]))) %>%
  setNames(length(unique(tcrsCircosQcCd8[, sampleColumnCircosQcCd8, drop = TRUE])))

## set up color palette for sub-projects, using variations on a color scheme
# can use sample() around the colorRampPalette() calls to randomize the order of colors
samplePalCircosQcCd8 <-
  palDonorId[names(palDonorId) %in% tcrCellsCircosQcCd8$donorId]
tcrCellsCircosQcCd8$sampleCol <-
  samplePalCircosQcCd8[
    as.character(
      tcrCellsCircosQcCd8[
        , sampleColumnCircosQcCd8, drop = TRUE])]

groupPalCircosQcCd8 <-
  palCellTypeGroup[names(palCellTypeGroup) %in% tcrCellsCircosQcCd8$Cell.Type_CD8]
tcrCellsCircosQcCd8$groupCol <-
  groupPalCircosQcCd8[
    as.character(
      tcrCellsCircosQcCd8[
        , groupColumnCircosQcCd8, drop = TRUE])]

tcrCellsCircosQcCd8 <-
  unique(tcrCellsCircosQcCd8[, c("libid", "sampleCol", "groupCol")]) %>%
  dplyr::rename(tcr1 = libid)

tcrCellsCircosQcCd8$tcr1 <-
  factor(tcrCellsCircosQcCd8$tcr1,
    levels = gtools::mixedsort(tcrCellsCircosQcCd8$tcr1))
tcrCellsCircosQcCd8 <-
  tcrCellsCircosQcCd8 %>%
  dplyr::arrange(tcr1)

## set colors of links (average sample colors of the two TCRs)
tcrLinksCircosQcCd8$sampleCol <-
  cbind(
    tcrCellsCircosQcCd8$sampleCol[
      match(tcrLinksCircosQcCd8$tcr1, tcrCellsCircosQcCd8$tcr1)],
    tcrCellsCircosQcCd8$sampleCol[
      match(tcrLinksCircosQcCd8$tcr2, tcrCellsCircosQcCd8$tcr1)]) # %>%
# apply(MARGIN = 1, FUN = miscHelpers::average_colors)
```

```{r plotCircosQcCd8, dependson="createObjectsPlotCircosQcCd8"}
## generate a circos plot with individuals and patient groups labeled
filenamePlotCircosQcCd8 <-
  paste0("circosQcCd8_noMAIT_by_", groupColumnCircosQcCd8, "_and_", sampleColumnCircosQcCd8,
    ".", filenameSuffix, ".pdf")
plot_TCR_circos(
  tcrCellsCircosQcCd8, tcrLinksCircosQcCd8,
  ring_colors = c("sampleCol", "groupCol"),
  link_colors = "sampleCol", link_width = "num_shared_chains",
  filename = file.path(plotDir, filenamePlotCircosQcCd8))
```

```{r plotCircosLegendsQcCd8, dependson="createObjectsPlotCircosQcCd8"}
## output color legends for incorporation downstream
# easier to output them separately and merge them in Illustrator
filenameCircosLegend1QcCd8 <-
  paste0("circosQcCd8_noMAIT_legend_", sampleColumnCircosQcCd8,
    ".", filenameSuffix, ".pdf")
pdf(
  file.path(plotDir, filenameCircosLegend1QcCd8),
  w = 5, h = 8)
plot.new()

legend(
  x = "topleft",
  title = "Donor ID",
  legend = names(samplePalCircosQcCd8), fill = samplePalCircosQcCd8,
  bty = "n", xpd = TRUE)

# # version for splitting legend into two columns
# legend(
#   x = "topleft",
#   legend=
#     names(samplePalCircosQcCd8)[
#       1:floor(length(samplePalCircosQcCd8)/2)],
#   fill=
#     samplePalCircosQcCd8[
#       1:floor(length(samplePalCircosQcCd8)/2)],
#   bty = "n", xpd=TRUE)
# legend(
#   x = "topright",
#   legend
#   =names(samplePalCircosQcCd8)[
#     ceiling((length(samplePalCircosQcCd8)+1)/2):length(samplePalCircosQcCd8)],
#   fill=
#     samplePalCircosQcCd8[
#       ceiling((length(samplePalCircosQcCd8)+1)/2):length(samplePalCircosQcCd8)],
#   bty = "n", xpd=TRUE)
invisible(dev.off())

# legend for groups
filenameCircosLegend2QcCd8 <-
  paste0("circosQcCd8_legend_", groupColumnCircosQcCd8,
    ".", filenameSuffix, ".pdf")
pdf(
  file.path(plotDir, filenameCircosLegend2QcCd8),
  w = 3, h = 3)
plot.new()
legend(
  x = "topleft",
  title = "Study group",
  legend = names(palCellTypeGroup), fill = palCellTypeGroup,
  bty = "n", xpd = TRUE)
invisible(dev.off())

```