---
title: "Distinct mechanisms of mismatch repair deficiency delineate two modes of response to PD-1 immunotherapy in endometrial carcinoma"
output: pdf_document
---

 - data reproduction of https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9905265/
 
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load necessary libraries

```{r}

library(Seurat)
library(SingleR)
library(ggplot2)
library(dplyr)

```

# Set theme

```{r}

theme_set(
  theme_bw(20) +
    theme(panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.border = element_rect(colour="black", fill = NA, size = 1),
          axis.text = element_text(colour="black"),
          axis.ticks = element_line(colour="black"),
          axis.text.x = element_text(angle=0),
          legend.title = element_text(size = 10),
          legend.text = element_text(size = 7)))

```

# Read in data

```{r}

tdat = readRDS("../saved_data/seurat_T_cells_pre_reduction.rds")

```

# Repeat dimensional reduction FindClusters since subsetting for T cells

```{r}

# exclude V/J genes that would otherwise dominate dimensional reduction and clustering
excluded_genes <- grep("^TRAV|^TRBV|^TRAJ|^TRBJ", rownames(tdat), value = TRUE)
included_genes <- setdiff(rownames(tdat), excluded_genes)

tdat <- RunPCA(tdat, npcs = 30, verbose = FALSE, genes.use = included_genes)
tdat <- RunUMAP(tdat, reduction = "pca", dims = 1:30)
tdat <- FindNeighbors(tdat, reduction = "pca", dims = 1:30, k.param = 200)
tdat <- FindClusters(tdat)

```

# Visualize UMAP by cluster

```{r}

DimPlot(tdat, reduction = "umap", label = TRUE, repel = TRUE)

```

# Re-check mito % across clusters

```{r}

tdat_mito_by_cluster <- as_tibble(tdat@meta.data) %>%
  select(propMt, seurat_clusters)

# Calculate the median propMt for each seurat_clusters group
median_values <- tdat_mito_by_cluster %>%
  group_by(seurat_clusters) %>%
  summarize(median_propMt = median(propMt))

# Reorder seurat_clusters based on median_propMt
tdat_mito_by_cluster$seurat_clusters <- factor(tdat_mito_by_cluster$seurat_clusters, 
                                                levels = median_values %>% 
                                                  arrange(desc(median_propMt)) %>%
                                                  pull(seurat_clusters))

# Create a ggplot with tilted x-axis labels and arranged x-axis
ggplot(tdat_mito_by_cluster, aes(x = seurat_clusters, y = propMt)) +
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 12))

```

# Remove clusters with uniformly high mitochondrial reads

```{r}

# remove clusters 25 & 31
clusters_to_remove <- WhichCells(tdat, idents = c(25, 31))

tdat_no_mito <- subset(tdat, cells = setdiff(Cells(tdat), clusters_to_remove))

```

# Save RDS

```{r}

saveRDS(tdat_no_mito, "../saved_data/seurat_T_cells_no_mito.rds")

```