---
title: "Joined analyses from both colitis datasets"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load necessary libraries

```{r}

library(ggplot2)
library(dplyr)
library(tidyr)
library(scales)
library(ggpubr)
library(Seurat)
library(Matrix)

```

# Set theme

```{r}

theme_set(
  theme_bw(20) +
    theme(panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.border = element_rect(colour="black", fill = NA, size = 1),
          axis.text = element_text(colour="black"),
          axis.ticks = element_line(colour="black"),
          axis.text.x = element_text(angle=0),
          legend.title = element_text(size = 10),
          legend.text = element_text(size = 7)))

```

# Read in data

```{r}

old_colitis <- readRDS("../../Molecular_Pathways_of_Colon_Inflammation_Induced_by_Cancer_Immunotherapy/saved_data/integrated.rds")

new_colitis <- readRDS("../../Molly_Fisher_colitis/saved_data/integrated.rds")

```

# Mark metadata for datasets

```{r}

old_colitis$dataset <- as.factor("2020_cell_luoma")

new_colitis$dataset <- as.factor("2021_biorxiv_thomas")

```

# Find integration features

```{r}

colon_qc.list <- c(old_colitis, new_colitis)

# select features that are repeatedly variable across datasets for integration
features <- SelectIntegrationFeatures(object.list = colon_qc.list, nfeatures = 3000)

# prep step
colon_qc.list <- PrepSCTIntegration(object.list = colon_qc.list, anchor.features = features)

# run PCA to allow rpca use later
colon_qc.list <- lapply(X = colon_qc.list, FUN = RunPCA, features = features)

```

# Find integration anchors

```{r}

# this command creates an 'integrated' data assay

immune.anchors <- FindIntegrationAnchors(object.list = colon_qc.list, normalization.method = "SCT", anchor.features = features, reduction = "rpca", k.anchor = 10, dims = 1:30)

```

# Integrate the data

```{r}

immune.combined <- IntegrateData(anchorset = immune.anchors, normalization.method = "SCT")

```

# Save RDS

```{r}

saveRDS(immune.combined, "../saved_data/integrated_from_integrated_colitis_datasets.rds")

```

