---
title: "Joined analyses of colitis datasets"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load necessary libraries

```{r}

library(ggplot2)
library(dplyr)
library(tidyr)
library(stringr)
library(scales)
library(ggpubr)
library(ComplexHeatmap)
library(e1071)

```

# Set theme

```{r}

theme_set(
  theme_bw(20) +
    theme(panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.border = element_rect(colour="black", fill = NA, size = 1),
          axis.text = element_text(colour="black"),
          axis.ticks = element_line(colour="black"),
          axis.text.x = element_text(angle=0),
          legend.title = element_text(size = 10),
          legend.text = element_text(size = 7)))

```

# Read in data

```{r}

luoma_data <- read.csv("../../luoma_cell_2020/saved_data/pre_feature_heatmap_data.csv") %>%
  mutate(dataset = "2020_cell_luoma") %>%
  select(-X)

thomas_data <- read.csv("../../thomas_biorxiv_2021/saved_data/pre_feature_heatmap_data.csv") %>%
  mutate(dataset = "2021_biorxiv_thomas") %>%
  rename(patient = patient_id) %>%
  select(-X)

combined_data <- thomas_data %>%
  full_join(luoma_data)

combined_data

seq_depth_luoma <- read.csv("../../luoma_cell_2020/saved_data/seq_depth.csv")

seq_depth_thomas <- read.csv("../../thomas_biorxiv_2021/saved_data/seq_depth.csv")

seq_depth <- seq_depth_luoma %>%
  full_join(seq_depth_thomas)

```

# Prep data for summary plots (normalized method)

```{r}

prepped_data <- combined_data %>%
  filter(group != "no ICI") %>%
  # normalize by sequencing depth
  left_join(seq_depth, by = c("patient", "group")) %>%
  mutate(normalized_count = count / seq_depth) %>%
  # look at just unique clonotypes from each patient
  group_by(patient, clonotype, Chain) %>%
  dplyr::slice(1) %>%
  ungroup() %>%
  group_by(predicted.celltype.l1, predicted.celltype.l2, Chain) %>%
  arrange(-normalized_count) %>%
  mutate(chunk_size = ceiling(n() * 0.05),
         chunk = 5*ceiling(row_number() / chunk_size))

prepped_data

```

# Define test functions

```{r}

# Function to perform the test within a specific bin of clonotype abundances
perform_wilcox_test <- function(data, cutoff) {
  result <- data %>%
    filter(chunk == cutoff) %>%
    group_by(predicted.celltype.l1, predicted.celltype.l2, Chain) %>%    
    summarize(
      p_val_pgen = {
        if(length(unique(group)) != 2 | any(table(group) == 1)) {
          NA
        } else {
          wilcox.test(pgen ~ group, exact = FALSE)$p.value
        }
      },
      p_val_cdr3_hydrophobicity = {
        if(length(unique(group)) != 2 | any(table(group) == 1)) {
          NA
        } else {
          wilcox.test(cdr3_hydrophobicity ~ group, exact = FALSE)$p.value
        }
      },
      p_val_cdr3_length = {
        if(length(unique(group)) != 2 | any(table(group) == 1)) {
          NA
        } else {
          wilcox.test(cdr3_length ~ group, exact = FALSE)$p.value
        }
      }
    ) %>%
    ungroup()
  
  return(result)
}

# Function to perform the test cumulativley up to a specific bin of clonotype abundances
perform_wilcox_test_cumulatively <- function(data, cutoff) {
  result <- data %>%
    filter(chunk <= cutoff) %>%
    group_by(predicted.celltype.l1, predicted.celltype.l2, Chain) %>%    
    summarize(
      p_val_pgen = {
        if(length(unique(group)) != 2 | any(table(group) == 1)) {
          NA
        } else {
          wilcox.test(pgen ~ group, exact = FALSE)$p.value
        }
      },
      p_val_cdr3_hydrophobicity = {
        if(length(unique(group)) != 2 | any(table(group) == 1)) {
          NA
        } else {
          wilcox.test(cdr3_hydrophobicity ~ group, exact = FALSE)$p.value
        }
      },
      p_val_cdr3_length = {
        if(length(unique(group)) != 2 | any(table(group) == 1)) {
          NA
        } else {
          wilcox.test(cdr3_length ~ group, exact = FALSE)$p.value
        }
      }
    ) %>%
    ungroup()
  
  return(result)
}

```

# Perform wilcox rank sum tests within chunks of 5% clonotypes (normalized method)

```{r}

# List to store results
results_list <- list()

# Iterate through chunk cutoffs
for (num in 1:5) {
  result <- prepped_data %>%
    perform_wilcox_test_cumulatively(cutoff = num*5)

  results_list[[as.character(num*5)]] <- result
}

# Combine results into a single dataframe
results_df <- bind_rows(results_list, .id = "Chunk")

results_df <- results_df %>%
  pivot_longer(cols = c("p_val_pgen", "p_val_cdr3_length", "p_val_cdr3_hydrophobicity"), names_to = "p_val") %>%
  rename(p_val_category = p_val) %>%
  mutate(p_val_category = gsub("p_val_", "", p_val_category)) %>%
  mutate(category = paste(predicted.celltype.l2, Chain, p_val_category)) %>%
  # adjust pvals for multiple comparisons
  mutate(value = p.adjust(value, method = "BH")) %>%
  arrange(value)

results_df

```

# Make heatmap (normalized method)

```{r}

top_results <- results_df %>%
  mutate(category = paste(predicted.celltype.l2, Chain, p_val_category))

filtered_results_df <- results_df %>%
  filter(category %in% top_results$category) %>%
  mutate(log_val = -log10(value))

filtered_results_df$Chunk <- factor(filtered_results_df$Chunk, levels = c("5", "10", "15", "20", "25"))

heatmap_df <- filtered_results_df %>%
  select(-value, -category) %>%
  rename(value = log_val) %>%
  mutate(p_val_category = case_when(
    p_val_category == "pgen" ~ "Probability of generation",
    p_val_category == "cdr3_length" ~ "CDR3 length (AAs)",
    p_val_category == "cdr3_hydrophobicity" ~ "CDR3 hydrophobicity"
  )) %>%
  mutate(predicted.celltype.l2 = gsub("CD4 |CD8 ", "", predicted.celltype.l2))

heatmap_df

# Prepare the data in matrix form
heatmap_data <- reshape2::dcast(heatmap_df, predicted.celltype.l1 + predicted.celltype.l2 + p_val_category + Chain ~ Chunk, value.var = "value")

# Extract value columns
mat <- as.matrix(heatmap_data[, -(1:4)])

# Set row names
rownames(mat) <- paste(heatmap_data$predicted.celltype.l1, heatmap_data$predicted.celltype.l2, heatmap_data$p_val_category, heatmap_data$Chain, sep = "_")

# Create a matrix of annotations
chain_annotations <- cbind(
  Chain = heatmap_data$Chain
)

# Create a matrix of annotations
type_annotations <- cbind(
  "Cell type" = heatmap_data$predicted.celltype.l1
)

# Create a matrix of annotations
subtype_annotations <- cbind(
  "Cell subtype" = heatmap_data$predicted.celltype.l2
)

# Create a matrix of annotations
feature_annotations <- cbind(
  Feature = heatmap_data$p_val_category
)

# Plot the heatmap without clustering
Heatmap(mat,
        cluster_rows = FALSE,
        cluster_columns = FALSE,
        row_names_gp = gpar(fontsize = 8),  # Adjust font size if needed
        right_annotation = rowAnnotation("Cell type" = type_annotations,
                                         "Cell subtype" = subtype_annotations,
                                         Chain = chain_annotations,
                                         Feature = feature_annotations,
                                         col = list("Cell type" = c("CD4 T" = "#fde725", "CD8 T" = "#21918c", "other T" = "#440154"),
                                                    "Chain" = c("TRA" = "#fde725", "TRB" = "#440154"),
                                                    "Cell subtype" = c("dnT" = "#440154", "Treg" = "#46327e", "Proliferating" = "#1fa187", "TCM" = "#277f8e",   "TEM" = "#365c8d", "Naive" = "#4ac16d", "MAIT" = "#a0da39", "CTL" = "#fde725", "Trm" = "black"),
                                                    "Feature" = c("CDR3 length (AAs)" = "#21918c", "CDR3 hydrophobicity" = "#fde725", "Probability of generation" = "#440154"))),
        show_row_names = FALSE,
        column_title = "Clonotypes bins\n(% of repertoire across patients)",
        column_title_side = "bottom",
        heatmap_legend_param = list(title = "Wilcox padj val (-log10) for\nyes vs. no colitis irAE"),
        layer_fun = function(j, i, x, y, width, height, fill) {
          v = pindex(mat, i, j)
          l = v > -log10(0.05) & v < -log10(0.01) & !is.na(v)
          if (any(l)) {
            grid.text("*", x[l], y[l], gp = gpar(fontsize = 10))
          }
          q = v > -log10(0.01) & !is.na(v)
          if (any(q)) {
            grid.text("**", x[q], y[q], gp = gpar(fontsize = 10))
          }
        }
      )

```