---
title: "Molecular Pathways of Colon Inflammation Induced by Cancer Immunotherapy"
output: pdf_document
---

 - data mining of https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7415717/
 
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load necessary libraries

```{r}

library(ggplot2)
library(dplyr)
library(stringr)
library(tidyr)
library(tcrGraph)
library(tidyverse)
library(igraph)
library(graphlayouts)
library(ggraph)
library(viridis)
library(gridExtra)

```

# Set theme

```{r}

theme_set(
  theme_bw(20) +
    theme(panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.border = element_rect(colour="black", fill = NA, size = 1),
          axis.text = element_text(colour="black"),
          axis.ticks = element_line(colour="black"),
          axis.text.x = element_text(angle=0),
          legend.title = element_text(size = 10),
          legend.text = element_text(size = 7)))

```

# Make highly expanded TCR df

```{r}

tcrs <- read.csv("../saved_data/tcr_graph_input.csv") %>%
  dplyr::select(-X) %>%
  mutate(clonotype = paste(v_gene, j_gene, cdr3, sep = "_")) %>%
  group_by(patient, clonotype, chain) %>%
  mutate(count = n()) %>%
  ungroup() %>%
  # look at highly expanded per patient
  group_by(patient, chain) %>%
  arrange(-count) %>%
  dplyr::slice_head(n = 350) %>%
  ungroup() %>%
  dplyr::rename(libid = barcode)

tcrs

```

# Make TCR graph with Igraph: no irAE

```{r}

no_irae_tcrs <- tcrs %>%
  filter(group == "ICI no colitis") %>%
  # exclude singletons
  group_by(libid) %>%
  filter(n() > 1) %>%
  ungroup()

no_irae_tcr_graph <- makeTcrGraph(no_irae_tcrs, link = "nt")

no_irae_tcr_igraph <- tcrGraphToIgraph(no_irae_tcr_graph)

V(no_irae_tcr_igraph)$`Number of Cells` <- V(no_irae_tcr_igraph)$value
V(no_irae_tcr_igraph)$Chain <- V(no_irae_tcr_igraph)$group

dev.new(width = 9.5, length = 8)
theme_set(theme_bw(20) + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + theme(legend.key = element_blank()))
ggraph(no_irae_tcr_igraph, "fr") +
    geom_edge_link(
        edge_width = 1,
        #edge_color = edgeColor
    ) +
    geom_node_point(
        aes(fill = Chain, size = `Number of Cells`),
        shape = 21,
        color = "black"
    ) +
    #scale_fill_manual(values = nodePalette) +
    guides(fill = guide_legend(override.aes = list(size = 5))) +
    ggtitle("no irAE TCRs")

# Compute the average connectivity
num_edges <- ecount(no_irae_tcr_igraph)
num_vertices <- vcount(no_irae_tcr_igraph)
average_connectivity <- 2 * num_edges / num_vertices

# Print the results
cat("Average Connectivity (no irAE):", average_connectivity, "\n")
cat("Number of Edges (no irAE):", num_edges, "\n")
cat("Number of Vertices (no irAE):", num_vertices, "\n")

```

# Make TCR graph with Igraph: yes irAE

```{r}

irae_tcrs <- tcrs %>%
  filter(group == "ICI colitis") %>%
  # exclude singletons
  group_by(libid) %>%
  filter(n() > 1) %>%
  ungroup()

irae_tcr_graph <- makeTcrGraph(irae_tcrs, link = "nt")

irae_tcr_igraph <- tcrGraphToIgraph(irae_tcr_graph)

V(irae_tcr_igraph)$`Number of Cells` <- V(irae_tcr_igraph)$value
V(irae_tcr_igraph)$Chain <- V(irae_tcr_igraph)$group

dev.new(width = 9.5, length = 8)
theme_set(theme_bw(20) + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + theme(legend.key = element_blank()))
ggraph(irae_tcr_igraph, "fr") +
    geom_edge_link(
        edge_width = 1,
        #edge_color = edgeColor
    ) +
    geom_node_point(
        aes(fill = Chain, size = `Number of Cells`),
        shape = 21,
        color = "black"
    ) +
    #scale_fill_manual(values = nodePalette) +
    guides(fill = guide_legend(override.aes = list(size = 5))) +
    ggtitle("irAE TCRs")

# Compute the average connectivity
num_edges <- ecount(irae_tcr_igraph)
num_vertices <- vcount(irae_tcr_igraph)
average_connectivity <- 2 * num_edges / num_vertices

# Print the results
cat("Average Connectivity (irAE):", average_connectivity, "\n")
cat("Number of Edges (irAE):", num_edges, "\n")
cat("Number of Vertices (irAE):", num_vertices, "\n")

```

# Read in convergence df

```{r}

convergence <- read.csv("../saved_data/converged_public_private_tcrs.csv") %>%
  select(-X) %>%
  select(barcode, group, Chain, v_gene, d_gene, j_gene, c_gene, convergence) %>%
  dplyr::rename(chain = Chain)

convergence

```

# Test convergence vs. connectivity

 - take random subsets and get connectivity and convergence fraction metrics, see if they correlate over many random subsets (irAE vs. no irAE as well)

```{r}

sample_and_analyze <- function(df, n) {
  results <- vector("list", n)
  
  for (i in 1:n) {
    # Sample the dataframe
    sampled_df <- df %>%
      sample_n(500, replace = FALSE)
    
    # Create the TCR graph
    tcr_graph <- makeTcrGraph(sampled_df, link = "nt")
    tcr_igraph <- tcrGraphToIgraph(tcr_graph)
    
    # Compute average connectivity
    num_edges <- ecount(tcr_igraph)
    num_vertices <- vcount(tcr_igraph)
    average_connectivity <- 2 * num_edges / num_vertices
    
    # Compute fraction of 'Yes' values in the convergence column
    convergence_fraction <- mean(sampled_df$convergence == 'Yes', na.rm = TRUE)
    
    # Store the results
    results[[i]] <- list(average_connectivity = average_connectivity,
                         convergence_fraction = convergence_fraction)
  }
  
  return(results)
}

# Load data and preprocess
random_irae_tcrs <- read.csv("../saved_data/tcr_graph_input.csv") %>%
  dplyr::select(-X) %>%
  left_join(convergence, by = c("barcode", "group", "chain", "v_gene", "d_gene", "j_gene", "c_gene")) %>%
  filter(group == "ICI colitis") %>%
  dplyr::rename(libid = barcode)

# Call the function to sample and analyze
n_times <- 100
results <- sample_and_analyze(random_irae_tcrs, n_times)

# Extract average connectivity and convergence fraction from results
average_connectivity <- unlist(lapply(results, function(x) x$average_connectivity))
convergence_fraction <- unlist(lapply(results, function(x) x$convergence_fraction))

# Create a dataframe for plotting
plot_data <- data.frame(
  Average_Connectivity = average_connectivity,
  Convergence_Fraction = convergence_fraction
)

ggplot(plot_data, aes(x = Average_Connectivity, y = Convergence_Fraction)) +
  geom_point() +
  labs(x = "Average Connectivity", y = "Convergence Fraction")

```