---
title: "Molecular Pathways of Colon Inflammation Induced by Cancer Immunotherapy"
output: pdf_document
---

 - data mining of https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7415717/
 
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load necessary libraries

```{r}

library(Seurat)
library(Matrix)
library(ggplot2)
library(dplyr)
library(tidyr)
library(stringr)
library(circlize)
library(vegan)

```

# Set theme

```{r}

theme_set(
  theme_bw(20) +
    theme(panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.border = element_rect(colour="black", fill = NA, size = 1),
          axis.text = element_text(colour="black"),
          axis.ticks = element_line(colour="black"),
          axis.text.x = element_text(angle=0),
          legend.title = element_text(size = 10),
          legend.text = element_text(size = 7)))

```

# Read in data

```{r}

rna_tcr <- read.csv("../saved_data/rna_tcr_no_na_good_cell_typing.csv")

rna_tcr <- rna_tcr %>%
  mutate(predicted.celltype.l2 = if_else(seurat_clusters %in% c(25, 27), "CD4 Trm", if_else(seurat_clusters %in% c(3, 7, 9, 15, 16), "CD8 Trm", predicted.celltype.l2))) %>%
  bind_rows(mutate(rna_tcr, predicted.celltype.l1 = "All T cells"))

```

# Analyze diversity

```{r}

cdr3_amino_acid_diversity_df <- rna_tcr %>%
  filter(!(is.na(cdr3)),
         Chain != "Multi",
         group != "no ICI") %>%
  group_by(cdr3, Chain, orig.ident, group, predicted.celltype.l2) %>%
  mutate(cdr3_amino_acid_count = n()) %>%
  ungroup() %>%
  group_by(orig.ident, Chain, predicted.celltype.l2) %>%
  # Calculate Shannon diversity index (H)
  mutate(shannon = diversity(cdr3_amino_acid_count),
         inv_shannon = 1/diversity(cdr3_amino_acid_count)) %>%
  slice(1) %>%
  ungroup() %>%
  select(Chain, group, orig.ident, shannon, inv_shannon, predicted.celltype.l2)
  #group_by(Chain, predicted.celltype.l2) %>%
  #summarize(
  #    p_val_diveristy = {
  #      if(length(unique(group)) != 2 | any(table(group) == 1)) {
  #        NA
  #      } else {
  #        wilcox.test(shannon ~ group, exact = FALSE)$p.value
  #      }
  #    }) %>%
  #ungroup() %>%
  #mutate(p_val_diveristy = p.adjust(p_val_diveristy, method = "BH")) %>%
  #arrange(p_val_diveristy)

cdr3_amino_acid_diversity_df

#TRA	CD4 Proliferating	0.03841870		
#TRA	CD8 Naive	0.03841870		
#TRA	CD8 TEM	0.03841870		
#TRA	Treg	0.03841870		
#TRB	CD4 Proliferating	0.03841870		
#TRB	CD8 Naive	0.03841870		
#TRB	CD8 TEM	0.03841870		
#TRB	Treg	0.03841870	

cdr3_amino_acid_diversity_df$group <- factor(cdr3_amino_acid_diversity_df$group, levels = c("no ICI", "ICI no colitis", "ICI colitis"))

p <- ggplot(cdr3_amino_acid_diversity_df %>% filter(predicted.celltype.l2 %in% c("CD4 Proliferating", "CD8 Naive", "CD8 TEM", "Treg")), aes(x = Chain, y = shannon, fill = group)) +
  geom_boxplot() +
  facet_wrap(~ predicted.celltype.l2, scales = "free_y") +
  labs(x = "Chain",
       y = "Shannon entropy",
       fill = "Group")

# Adjust y-axis scales with a specified number of ticks
p + scale_y_continuous(expand = expansion(mult = c(0.1, 0.5)), breaks = pretty_breaks(n = 3))

# Shannon entropy: 0 means monoclonal, higher means polyclonal, weights richness (total # of unique clones) over evenness

# Filter the data for statistical test
#test_data <- cdr3_amino_acid_diversity_df %>%
#  filter(Chain == "TRB",
#         predicted.celltype.l2 == "CD4 Proliferating",
#         group != "no ICI")

# Calculate the Wilcoxon rank-sum test statistic and p-value
#wilcox_result <- wilcox.test(test_data$shannon ~ test_data$group)

# Print the results
#print(wilcox_result)

```