---
title: "Molecular Pathways of Colon Inflammation Induced by Cancer Immunotherapy"
output: pdf_document
---

 - data mining of https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7415717/
 
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load necessary libraries

```{r}

library(ggplot2)
library(dplyr)
library(tidyr)
library(scales)
library(Seurat)

```

# Set theme

```{r}

theme_set(
  theme_bw(20) +
    theme(panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.border = element_rect(colour="black", fill = NA, size = 1),
          axis.text = element_text(colour="black"),
          axis.ticks = element_line(colour="black"),
          axis.text.x = element_text(angle=0),
          legend.title = element_text(size = 10),
          legend.text = element_text(size = 7)))

```

# Read in data

```{r}

feature_df <- read.csv("../saved_data/rna_tcr_no_na_good_cell_typing.csv")

feature_df

```

# Prep table of cell type (l2) vs. irAE

```{r}

contingency_table <- table(feature_df$group, feature_df$predicted.celltype.l2)

contingency_table

# Perform Chi-square test
chi_square_result <- chisq.test(contingency_table)

# Display the test result
print(chi_square_result)

```

# Read in data for UMAP contour plot

```{r}

seurat_obj <- readRDS("../saved_data/T_cells.rds")

downsampled_df <- read.csv("../saved_data/downsampled_df.csv")

downsampled_seurat <- subset(seurat_obj, cells = downsampled_df$barcode)

```

# Make UMAP contour plot

```{r}

DimPlot(downsampled_seurat, reduction = "umap", group.by = "predicted.celltype.l2", label = TRUE, label.size = 3 , repel = TRUE)

data <- Embeddings(object = downsampled_seurat[["umap"]])[(colnames(downsampled_seurat)), c(1, 2)]
data <- as.data.frame(data)
data$celltype <- downsampled_seurat@meta.data$predicted.celltype.l2
data$patient_ID <- downsampled_seurat@meta.data$orig.ident

data <- data %>%
  filter(!(grepl("^CT", patient_ID))) %>%
  filter(celltype %in% c("CD4 Proliferating", "CD8 Proliferating", "CD4 TEM", "CD8 TCM", "MAIT")) %>%
  mutate(irAE = if_else(grepl("^NC", patient_ID), "no colitis", "colitis"))

data$irAE <- factor(data$irAE, levels = c("no colitis", "colitis"))

ggplot(data) +
  geom_point(aes(x=umap_1, y=umap_2, color=celltype), show.legend = TRUE, size = 0.01) +
  facet_wrap(~ irAE) +
  geom_density2d(aes(x=umap_1, y=umap_2)) +
  theme(legend.text = element_text(size = 12),
        legend.title = element_text(size = 14))

```

# Make a plot of cell type abundances within each patient by irAE group (normalized by seq depth)

```{r}

cell_abundance_df <- feature_df %>%
  group_by(patient, predicted.celltype.l2, group) %>%
  summarize(count = n()) %>%
  ungroup() %>%
  group_by(patient) %>%
  mutate(normalized_count = count / sum(count)) %>%
  # filter for just subtypes of interest
  filter(predicted.celltype.l2 %in% c("CD4 Proliferating", "CD8 Proliferating", "CD4 TEM", "CD8 TCM", "MAIT"),
         group != "no ICI")

cell_abundance_df

cell_abundance_df$group <- factor(cell_abundance_df$group, levels = c("no ICI", "ICI no colitis", "ICI colitis"))

ggplot(cell_abundance_df, aes(x = predicted.celltype.l2, y = log10(normalized_count), fill = group)) +
  geom_boxplot() +
  labs(x = "", fill = "group", y = "Normalized cell\nproportion (log10)") +
  scale_y_continuous(expand = expansion(mult = c(0.1, 0.5)), breaks = pretty_breaks(n = 3)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 10))

# Filter the data for statistical test
test_data <- cell_abundance_df %>%
  filter(predicted.celltype.l2 == "MAIT",
         group != "no ICI")

# Calculate the Wilcoxon rank-sum test statistic and p-value
wilcox_result <- wilcox.test(test_data$normalized_count ~ test_data$group)

# Print the results
print(wilcox_result)

# CD4 TEM: 0.000666
# CD4 Proliferating: 0.004662
# CD8 Proliferating: 0.04444
# CD8 TCM: 0.002664
# MAITs: 0.000666

```

# Make a plot of cell type abundances within each patient by irAE group (downsampled)

```{r}

cell_abundance_df_downsampled <- downsampled_df %>%
  group_by(patient, predicted.celltype.l2, group) %>%
  summarize(count = n()) %>%
  ungroup() %>%
  # filter for just subtypes of interest
  filter(predicted.celltype.l2 %in% c("CD4 Proliferating", "CD8 Proliferating", "CD4 TEM", "CD8 TCM", "MAIT"),
         group != "no ICI")

cell_abundance_df_downsampled

cell_abundance_df_downsampled$group <- factor(cell_abundance_df_downsampled$group, levels = c("no ICI", "ICI no colitis", "ICI colitis"))

ggplot(cell_abundance_df_downsampled, aes(x = predicted.celltype.l2, y = log10(count), fill = group)) +
  geom_boxplot() +
  labs(x = "", fill = "group", y = "Cell proportion\n(log10)") +
  scale_y_continuous(expand = expansion(mult = c(0.1, 0.5)), breaks = pretty_breaks(n = 3)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 10))

# Filter the data for statistical test
test_data <- cell_abundance_df_downsampled %>%
  filter(predicted.celltype.l2 == "CD4 TEM",
         group != "no ICI")

# Calculate the Wilcoxon rank-sum test statistic and p-value
wilcox_result <- wilcox.test(test_data$count ~ test_data$group)

# Print the results
print(wilcox_result)

# CD4 TEM: 0.000666
# CD4 Proliferating: 0.004662
# CD8 Proliferating: 0.04949
# CD8 TCM: 0.004662
# MAITs: 0.000666

```