---
title: "T cell characteristics associated with irAE from ICI in melanoma"
output: pdf_document
---

 - data reproduction of https://www.nature.com/articles/s41591-021-01623-z

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load necessary libraries

```{r}

library(Seurat)
library(patchwork)
library(ggplot2)
library(dplyr)
library(tidyr)
library(tidyverse)
library(forcats)
library(vegan)
library(readxl)

```

# Set theme

```{r}

theme_set(
  theme_bw(20) +
    theme(panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.border = element_rect(colour="black", fill = NA, size = 1),
          axis.text = element_text(colour="black"),
          axis.ticks = element_line(colour="black"),
          axis.text.x = element_text(angle=0),
          legend.title = element_text(size = 10),
          legend.text = element_text(size = 7)))

```

# Read in data

```{r}

cleaned_seurat <- readRDS("../saved_data/mono_dc_rbc_platelet_filtered_tcr_bcr_checked_cell_type_clustered.rds")

```

# Create features for UMAP overlay

```{r}

# Create clonal expansion count buckets
feature_df <- as_tibble(cleaned_seurat@meta.data)

feature_df$cell_type <- Idents(cleaned_seurat)

feature_df <- feature_df %>%
  select(patient.ID, cell_type, CDR3.AA.Sequence, CDR3.NT.Sequence, CR.type) %>%
  group_by(patient.ID, CDR3.NT.Sequence) %>%
  mutate(cdr3_nt_count = n()) %>%
  mutate(expansion_group = if_else(
        is.na(CR.type), "no TCR/BCR info",
        ifelse(cdr3_nt_count <= 1, "single",
        ifelse(cdr3_nt_count <= 5, "small",
          ifelse(cdr3_nt_count <= 20, "medium",
            ifelse(cdr3_nt_count <= 100, "large",
              "hyperexpanded")))))) %>%
  ungroup() %>%
  mutate(CDR3_length = nchar(CDR3.AA.Sequence))

cleaned_seurat@meta.data$expansion_group <- feature_df$expansion_group
cleaned_seurat@meta.data$cdr3_aa_length <- feature_df$CDR3_length

```

# Plot UMAP with color of expansion count (bucketed)

```{r}

# Reorder factor levels so that "no TCR group" is plotted first
cleaned_seurat@meta.data$expansion_group <- factor(cleaned_seurat@meta.data$expansion_group, levels = c("no TCR/BCR info", "single", "small", "medium", "large", "hyperexpanded"))

DimPlot(cleaned_seurat, reduction = "umap", group.by = "expansion_group", shuffle = TRUE, seed = 992)

ggsave("../figures/umap_expansion_group_no_mono_dc.svg")

```